[buildPlans.IosevkaNeat]
family = "Iosevka Neat"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaNeat.variants]
  inherits = "ss14"


    [buildPlans.IosevkaNeat.variants.design]
    one = "no-base"
    three = "two-arcs"
    four = "semi-open-serifless"
    five = "oblique-arched-serifless"
    six = "open-contour"
    seven = "bend-serifless"
    eight = "crossing"
    nine = "open-contour"
    zero = "oval-slashed"
    capital-k = "symmetric-connected-serifless"
    capital-w = "straight-serifless"
    b = "toothless-corner-serifless"
    g = "single-storey-flat-hook-earless-corner"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "earless-single-arch-serifless"
    n = "earless-corner-straight-serifless"
    q = "earless-corner-straight-serifless"
    y = "straight-turn-serifless"
    paren = "normal"
    brace = "curly"
    number-sign = "upright"
    ampersand = "et-toothless-corner"
    at = "fourfold-solid-inner"
    percent = "rings-segmented-slash"
    question = "smooth"

    [buildPlans.IosevkaNeat.variants.italic]
    one = "no-base"
    three = "two-arcs"
    four = "semi-open-serifless"
    five = "oblique-arched-serifless"
    six = "open-contour"
    seven = "bend-serifless"
    eight = "crossing"
    nine = "open-contour"
    zero = "oval-slashed"
    capital-k = "symmetric-connected-serifless"
    capital-w = "straight-serifless"
    a = "single-storey-earless-corner-serifed"
    b = "toothless-corner-serifless"
    g = "single-storey-earless-corner"
    j = "serifed"
    k = "cursive-serifless"
    l = "tailed-serifed"
    m = "earless-single-arch-serifless"
    n = "earless-corner-straight-serifless"
    q = "earless-corner-straight-serifless"
    t = "bent-hook-short-neck"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    paren = "normal"
    brace = "curly"
    number-sign = "upright"
    ampersand = "et-toothless-corner"
    at = "fourfold-solid-inner"
    percent = "rings-segmented-slash"
    question = "smooth"

[buildPlans.IosevkaNeat.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaNeat.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaNeat.widths.Normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaNeat.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaNeat.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
