[buildPlans.IosevkaExtended]
family = "Iosevka Extended"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaExtended.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaExtended.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaExtended.widths.Normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaExtended.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaExtended.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
