[buildPlans.IosevkaNeat]
family = "Iosevka Neat"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaNeat.variants]
  inherits = "ss14"


    [buildPlans.IosevkaNeat.variants.design]
    capital-k = "symmetric-connected-serifless"
    capital-w = "straight-serifless"
    b = "toothless-corner-serifless"
    g = "single-storey-flat-hook-earless-corner"
    i = "hooky"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "earless-single-arch-serifless"
    n = "earless-corner-straight-serifless"
    q = "earless-corner-straight-serifless"
    y = "straight-turn-serifless"
    zero = "oval-top-right-cutout"
    one = "no-base"
    three = "two-arcs"
    four = "closed-serifless"
    five = "oblique-arched-serifless"
    six = "open-contour"
    seven = "bend-serifless"
    eight = "crossing-asymmetric"
    nine = "open-contour"
    paren = "normal"
    brace = "curly"
    number-sign = "upright"
    ampersand = "et-toothless-corner"
    at = "fourfold-solid-inner"
    question = "smooth"

[buildPlans.IosevkaNeat.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaNeat.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaNeat.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaNeat.widths.Condensed]
shape = 500
menu = 4
css = "condensed"

[buildPlans.IosevkaNeat.widths.Normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaNeat.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaNeat.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaSeriousCondensed]
family = "Iosevka Serious Condensed"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaSeriousCondensed.variants.design]
two = "straight-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
zero = "slashed-split"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-m = "hanging-serifless"
capital-q = "crossing"
capital-w = "straight-serifless"
f = "flat-hook-serifless"
i = "hooky"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless-serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
w = "straight-serifless"
y = "straight-turn-serifless"
long-s = "flat-hook-serifless"
lower-gamma = "straight"
lower-lambda = "tailed-turn"
lower-upsilon = "straight-serifless"
lower-chi = "semi-chancery-straight-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
asterisk = "penta-high"
paren = "large-contour"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold-solid-inner"
percent = "rings-continuous-slash"
micro-sign = "tailed-serifless"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.IosevkaSeriousCondensed.variants.italic]
two = "straight-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
zero = "slashed-split"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-m = "hanging-serifless"
capital-q = "crossing"
capital-w = "straight-serifless"
a = "single-storey-serifless"
d = "toothed-serifless"
f = "flat-hook-tailed"
i = "hooky"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed-flat-tailed"
r = "hookless-serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
w = "straight-serifless"
y = "straight-turn-serifless"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-serifless"
lower-gamma = "straight"
lower-lambda = "tailed-turn"
lower-upsilon = "straight-serifless"
lower-chi = "semi-chancery-straight-serifless"
cyrl-ve = "standard-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-ef = "serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"
asterisk = "penta-high"
paren = "large-contour"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold-solid-inner"
percent = "rings-continuous-slash"
micro-sign = "tailed-serifless"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.IosevkaSeriousCondensed.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaSeriousCondensed.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaSeriousCondensed.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaPlexish]
family = "Iosevka Plexish"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaPlexish.variants]
  inherits = "ss15"

    [buildPlans.IosevkaPlexish.variants.design]
    six = "straight-bar"
    seven = "straight-serifless"
    nine = "straight-bar"
    zero = "slashed-split"
    capital-g = "toothless-corner-serifless-hooked"
    a = "double-storey-serifless"
    b = "toothless-corner-serifless"
    g = "single-storey-serifless"
    k = "symmetric-touching-serifless"
    r = "serifed"
    y = "straight-serifless"
    capital-eszet = "flat-top-serifless"
    eszet = "sulzbacher-serifless"
    at = "fourfold-solid-inner"

[buildPlans.IosevkaPlexish.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaPlexish.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaPlexish.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaWest]
family = "Iosevka West"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaWest.variants.design]
two = "straight-neck-serifless"
three = "flat-top-serifless"
five = "oblique-arched-serifless"
eight = "two-circles"
zero = "slashed-split"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-serifless"
j = "flat-hook-serifed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
w = "straight-flat-top-serifless"
punctuation-dot = "square"
braille-dot = "square"
asterisk = "penta-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
dollar = "through"
percent = "rings-continuous-slash"
question = "corner"

[buildPlans.IosevkaWest.variants.italic]
two = "straight-neck-serifless"
three = "flat-top-serifless"
five = "oblique-arched-serifless"
eight = "two-circles"
zero = "slashed-split"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-tailed"
j = "flat-hook-serifed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
w = "straight-flat-top-serifless"
punctuation-dot = "square"
braille-dot = "square"
asterisk = "penta-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
dollar = "through"
percent = "rings-continuous-slash"
question = "corner"

[buildPlans.IosevkaWest.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaWest.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaWest.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaWest.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaWest.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaWestExtended]
family = "Iosevka West Extended"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaWestExtended.variants.design]
two = "straight-neck-serifless"
three = "flat-top-serifless"
five = "oblique-arched-serifless"
eight = "two-circles"
zero = "slashed-split"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-serifless"
j = "flat-hook-serifed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
w = "straight-flat-top-serifless"
punctuation-dot = "square"
braille-dot = "square"
asterisk = "penta-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
dollar = "through"
percent = "rings-continuous-slash"
question = "corner"

[buildPlans.IosevkaWestExtended.variants.italic]
two = "straight-neck-serifless"
three = "flat-top-serifless"
five = "oblique-arched-serifless"
eight = "two-circles"
zero = "slashed-split"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-tailed"
j = "flat-hook-serifed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
w = "straight-flat-top-serifless"
punctuation-dot = "square"
braille-dot = "square"
asterisk = "penta-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
dollar = "through"
percent = "rings-continuous-slash"
question = "corner"

[buildPlans.IosevkaWestExtended.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaWestExtended.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaWestExtended.widths.Normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaWestExtended.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaWestExtended.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
