[buildPlans.IosevkaExtended]
family = "Iosevka Extended"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaExtended.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaExtended.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaExtended.widths.Normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaExtended.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaExtended.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaPragmaExtended]
family = "Iosevka Pragma Extended"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaPragmaExtended.variants]
  inherits = "ss08"

    [buildPlans.IosevkaPragmaExtended.variants.design]
    zero = "oval-reverse-slashed-split"

[buildPlans.IosevkaPragmaExtended.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaPragmaExtended.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaPragmaExtended.widths.Normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaPragmaExtended.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaPragmaExtended.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
